commerce_forumpay.commerce_payment_gateway.plugin.forumpay_redirect:
  type: commerce_payment_gateway_configuration
  mapping:
    pos_id:
      type: string
      label: 'POS ID'
    api_user:
      type: string
      label: 'API User'
    api_key:
      type: string
      label: 'API Key'	 
  